package com.upsjb.ms1.domain.enums;

public enum TipoAuditoriaSeguridad {

    LOGIN_EXITOSO,
    LOGIN_FALLIDO,
    LOGOUT,
    LOGOUT_GLOBAL,

    REFRESH_TOKEN,
    REFRESH_TOKEN_REUTILIZADO,
    SESION_REVOCADA,

    USUARIO_CREADO,
    USUARIO_ACTUALIZADO,
    USUARIO_ACTIVADO,
    USUARIO_INACTIVADO,
    USUARIO_BLOQUEADO,
    USUARIO_DESBLOQUEADO,
    USUARIO_ELIMINADO,

    ROL_CREADO,
    ROL_ACTUALIZADO,
    ROL_ACTIVADO,
    ROL_INACTIVADO,
    ROL_ELIMINADO,
    ROL_CAMBIADO,

    PASSWORD_CAMBIADO,
    PASSWORD_RESET_SOLICITADO,
    PASSWORD_RESET_COMPLETADO,

    CODIGO_ENVIADO,
    CODIGO_VALIDADO,
    CODIGO_FALLIDO,
    CODIGO_EXPIRADO,
    CODIGO_BLOQUEADO,

    IP_NUEVA,
    IP_SOSPECHOSA,
    LOGIN_SOSPECHOSO,

    OAUTH2_LOGIN_EXITOSO,
    OAUTH2_LOGIN_FALLIDO,
    OAUTH2_CUENTA_VINCULADA,
    OAUTH2_CUENTA_DESVINCULADA,

    ACCESO_DENEGADO,
    TOKEN_INVALIDO,
    ERROR_SEGURIDAD
}